# Generated by Django 4.1 on 2022-08-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128, verbose_name='url')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all url granted to each of their groups.', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'router',
            },
        ),
    ]
