# Generated by Django 4.1 on 2022-08-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
