# Generated by Django 4.1 on 2022-08-20 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_profile_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 5, 12, 51, 220795, tzinfo=datetime.timezone.utc), verbose_name='创建时间'),
        ),
    ]
