# Generated by Django 4.1 on 2022-08-20 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_alter_profile_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 5, 13, 56, 412744), verbose_name='创建时间'),
        ),
    ]
