# Generated by Django 4.1 on 2022-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_alter_profile_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
