# Generated by Django 4.1 on 2022-08-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('permissions', '0007_alter_profile_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, verbose_name='path')),
                ('redirect', models.CharField(max_length=128, verbose_name='重定向地址')),
                ('name', models.CharField(max_length=128, verbose_name='路由名称')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('icon', models.CharField(max_length=128, verbose_name='图标')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all url granted to each of their groups.', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'routes1',
            },
        ),
        migrations.CreateModel(
            name='Routes2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, verbose_name='path')),
                ('component', models.CharField(max_length=128, verbose_name='组件')),
                ('name', models.CharField(max_length=128, verbose_name='路由名称')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
            ],
            options={
                'db_table': 'routes2',
            },
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
