# Generated by Django 4.1 on 2022-08-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_routes1_routes2_delete_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes1',
            name='component',
            field=models.CharField(default='layout/Layout', max_length=128, verbose_name='组件'),
        ),
    ]
