# Generated by Django 4.1 on 2022-08-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0009_routes1_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes2',
            name='routes1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.routes1'),
        ),
    ]
