# Generated by Django 4.1 on 2022-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0012_alter_routes1_groups_apipermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes1',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='路由名称'),
        ),
        migrations.AlterField(
            model_name='routes1',
            name='path',
            field=models.CharField(max_length=128, unique=True, verbose_name='path'),
        ),
    ]
