# Generated by Django 4.1 on 2022-08-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0013_alter_routes1_name_alter_routes1_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apipermission',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='apipermission',
            name='url',
            field=models.CharField(max_length=128, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='routes2',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='路由名称'),
        ),
        migrations.AlterField(
            model_name='routes2',
            name='path',
            field=models.CharField(max_length=128, unique=True, verbose_name='path'),
        ),
    ]
