# Generated by Django 4.1 on 2022-08-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0014_alter_apipermission_name_alter_apipermission_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes1',
            name='icon',
            field=models.CharField(blank=True, max_length=128, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='routes1',
            name='name',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='路由名称'),
        ),
        migrations.AlterField(
            model_name='routes1',
            name='redirect',
            field=models.CharField(blank=True, max_length=128, verbose_name='重定向地址'),
        ),
        migrations.AlterField(
            model_name='routes1',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='标题'),
        ),
    ]
