# Generated by Django 4.1 on 2022-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0015_alter_routes1_icon_alter_routes1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes1',
            name='component',
            field=models.CharField(blank=True, default='layout/Layout', max_length=128, verbose_name='组件'),
        ),
    ]
