# Generated by Django 4.1 on 2022-08-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0016_alter_routes1_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes1',
            name='path',
            field=models.CharField(error_messages={'blank': '1232412', 'unique': '这个路由已存在'}, max_length=128, unique=True, verbose_name='path'),
        ),
    ]
